create or replace TABLE ODS_DEV.PUBLIC.YYE_TEST (
	DATABASE_NAME VARCHAR(16777216) COMMENT '데이터베이스명',
	SCHEMA_NAME VARCHAR(16777216) COMMENT '스키마명',
	TABLE_NAME VARCHAR(16777216) COMMENT '테이블명',
	COLUMN_NAME VARCHAR(16777216) COMMENT '컬럼명',
	ORDINAL_POSITION NUMBER(9,0) COMMENT '컬럼순번',
	COLUMN_DEFAULT VARCHAR(16777216) COMMENT '기본값',
	DATA_TYPE VARCHAR(16777216) COMMENT '데이터타입명',
	IS_NULLABLE VARCHAR(3) COMMENT 'NULL허용여부',
	CHARACTER_MAXIMUM_LENGTH NUMBER(9,0) COMMENT '문자데이터길이',
	NUMERIC_PRECISION NUMBER(9,0) COMMENT '숫자데이터길이',
	NUMERIC_SCALE NUMBER(9,0) COMMENT '숫자데이터소수점길이',
	COMMENT VARCHAR(16777216) COMMENT '설명',
	SAMPLE_VALUES VARCHAR(16777216) COMMENT '샘플데이터',
	CREATE_TIMESTAMP TIMESTAMP_NTZ(9) COMMENT '생성일자'
);

create or replace TABLE SEOUL_DISTRICTLEVEL_DATA_FLOATING_POPULATION_CONSUMPTION_AND_ASSETS.GRANDATA.PROFILING (
	DATABASE_NAME VARCHAR(16777216) COMMENT '데이터베이스명',
	SCHEMA_NAME VARCHAR(16777216) COMMENT '스키마명',
	TABLE_NAME VARCHAR(16777216) COMMENT '테이블명',
	COLUMN_NAME VARCHAR(16777216) COMMENT '컬럼명',
	ORDINAL_POSITION NUMBER(9,0) COMMENT '컬럼순번',
	COLUMN_DEFAULT VARCHAR(16777216) COMMENT '기본값',
	DATA_TYPE VARCHAR(16777216) COMMENT '데이터타입명',
	IS_NULLABLE VARCHAR(3) COMMENT 'NULL허용여부',
	CHARACTER_MAXIMUM_LENGTH NUMBER(9,0) COMMENT '문자데이터길이',
	NUMERIC_PRECISION NUMBER(9,0) COMMENT '숫자데이터길이',
	NUMERIC_SCALE NUMBER(9,0) COMMENT '숫자데이터소수점길이',
	COMMENT VARCHAR(16777216) COMMENT '설명',
	SAMPLE_VALUES VARCHAR(16777216) COMMENT '샘플데이터',
	CREATE_TIMESTAMP TIMESTAMP_NTZ(9) COMMENT '생성일자'
);