create or replace task ODS_DEV.PUBLIC.TASK_ODS_TIME_MNG
	warehouse=COMPUTE_WH
	schedule='USING CRON 0,30 5-22 * * * Asia/Seoul'
	as CALL ODS_DEV.PUBLIC.SP_TIME_MNG('ODS', 5, 22, 0);

create or replace task ODS_DEV.PUBLIC.TASK_TO_ORDDET
	warehouse=COMPUTE_WH
	after ODS_DEV.PUBLIC.TASK_ODS_TIME_MNG
	when SYSTEM$GET_PREDECESSOR_RETURN_VALUE('TASK_ODS_TIME_MNG') = 'On schedule'
	as CALL ODS_DEV.PUBLIC.SP_ERP_TO_ORDDET('','HOUR',-1);
ALTER TASK ODS_DEV.PUBLIC.TASK_TO_ORDDET RESUME;
ALTER TASK ODS_DEV.PUBLIC.TASK_ODS_TIME_MNG RESUME;

create or replace task ODS_DEV.PUBLIC.TASK_PRC_SF_TIME_MNG
	warehouse=COMPUTE_WH
	schedule='USING CRON 15,45 5-22 * * * Asia/Seoul'
	as CALL ODS_DEV.PUBLIC.SP_TIME_MNG('PROCESS_SF', 5, 22, 15);
    
create or replace task ODS_DEV.PUBLIC.TASK_PRC_TO_ORDDET_SF
	warehouse=COMPUTE_WH
	after ODS_DEV.PUBLIC.TASK_PRC_SF_TIME_MNG
	when SYSTEM$GET_PREDECESSOR_RETURN_VALUE('TASK_PRC_SF_TIME_MNG') = 'On schedule'
	as CALL ODS_DEV.PUBLIC.SP_PRC_TO_ORDDET_SF('','HOUR',-1);

ALTER TASK ODS_DEV.PUBLIC.TASK_PRC_TO_ORDDET_SF RESUME;
ALTER TASK ODS_DEV.PUBLIC.TASK_PRC_SF_TIME_MNG RESUME;

create or replace task ODS_DEV.PUBLIC.TASK_PRC_AGG_TIME_MNG
	warehouse=COMPUTE_WH
	schedule='USING CRON 5 0 * * * Asia/Seoul'
	as CALL ODS_DEV.PUBLIC.SP_TIME_MNG('PROCESS_AGG', 0, 1, 5);